version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
    - .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    command: uvicorn main:app --host 0.0.0.0 --port ${BACKEND_PORT} --reload
    volumes:
      - ./app:/app
  postgres:
    image: postgres:13
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
    - .env
    restart: on-failure
    
